export const options = [
  {
    loja: "Lojas Maravilha - Matriz",
    cidade: "Matriz",
    endereco: "Av Cel Araujo Lima Nº 1004",
    bairro: "Centro",
    contato: "(88) 3411-6969 - (88) 99612-3347",
    email: "assistenciamaravilha@gmail.com",
  },
  {
    loja: "Lojas Maravilha - Palhano",
    cidade: "Palhano",
    endereco: "Rua do Cruzeiro Nº 319",
    bairro: "Centro",
    contato: "88 99783-0008",
    email: "assistenciamaravilha@gmail.com",
  },
  {
    loja: "Lojas Maravilha - Jaguaruana",
    cidade: "Jaguaruana",
    endereco: "Av Simão de Goes Nº 1468",
    bairro: "Centro",
    contato: "88 99612-3386",
    email: "assistenciamaravilha@gmail.com",
  },
  {
    loja: "Lojas Maravilha - Deposito",
    cidade: "Russas",
    endereco: "Rua Miguel Matis Neto Nº 72",
    bairro: "Catumbela",
    contato: "88 99612-3350",
    email: "assistenciamaravilha@gmail.com",
  },
  {
    loja: "Lojas Maravilha - Loja 05",
    cidade: "Russas",
    endereco: "Rua Padre Raul Vieira Nº 400",
    bairro: "Centro",
    contato: "88 99744-0048",
    email: "assistenciamaravilha@gmail.com",
  },
  {
    loja: "Lojas Maravilha - Limoeiro do Norte",
    cidade: "Limoeiro do Norte",
    endereco: "Rua Coronel Malveira Nº 2564",
    bairro: "Centro",
    contato: "88 99612-3258",
    email: "assistenciamaravilha@gmail.com",
  },
  {
    loja: "Lojas Maravilha - Itaiçaba",
    cidade: "Itaiçaba",
    endereco: "Rua Joaquim Romão Nº 54",
    bairro: "Centro",
    contato: "88 99612-3209",
    email: "assistenciamaravilha@gmail.com",
  },
  {
    loja: "Lojas Maravilha - Filial de Flores",
    cidade: "Filial Flores",
    endereco: "Avenida Raimundo Alves Nº 1849",
    bairro: "Centro",
    contato: "88 99612-3197",
    email: "assistenciamaravilha@gmail.com",
  },
  {
    loja: "Lojas Maravilha - Aracati",
    cidade: "Aracati",
    endereco: "Rua Coronel Alexandrino Nº 737",
    bairro: "Centro",
    contato: "88 99612-3142",
    email: "assistenciamaravilha@gmail.com",
  },
];
